### ISSUE TITLE
Point Details as new Vue.js page

### ISSUE THREAD

**Issue by radek2s** [SCADA-LTS/Scada-LTS#1532]
**Description**
Point Details as new Vue page will contain many smaller tasks like for example "Point Properties as new Vue.js page, or New fields in PointProperties" and so on. That is why this topic is kind of Epic task that has many dependent sub-tasks. 

**Expected Behavior**
Use REST API and Vue.js framework to display Point Details page with point properties section. It should have the same functionality as it was provided in classic Scada-LTS UI.  

**Actual Behavior**
Classic DWR JSP page. Vue page does not exists. 

**Sub-tasks**

- [x] #1518 New fields in PointProperties
- [x] #1531 Event Text Renderer Component
- [ ] #1563 Point Details as new Vue.js page - Tests

**Specifications**
Version: 2.6.0
Platform: Linux
