### ISSUE TITLE
DataSources as new Vue.js page all type

### ISSUE THREAD

**Issue by Limraj** [SCADA-LTS/Scada-LTS#2143]
## Current status

Most of the business logic has been created in the frontend side. There is still a need to create a DataSource API and the reliable endpoint that will serve and receive data from User Interface. Diagram with component relations is provided below.

3 of all 31 DataSource type definitions were implemented on the new UI.
- [ ] 1-wire
- [ ] ASCII File Reader
- [ ] ASCII Serial
- [ ] BACnet I/P
- [ ] DNP3 IP
- [ ] DNP3 Serial
- [ ] Dr.Storage HT-5B
- [ ] Galil DMC-21x2
- [ ] HTTP Image
- [ ] HTTP Receiver
- [ ] HTTP Retriever
- [ ] IEC101 Ethernet
- [ ] IEC101 Serial
- [ ] Internal Data Source
- [ ] JMX
- [ ] M Bus
- [ ] Meta Data Source
- [ ] Mitsubishi Alpha2
- [x] Modbus IP
- [ ] Modbus Serial
- [ ] NMEA listener
- [ ] OPC DA
- [ ] OpenV4J
- [ ] Pachube
- [ ] POP3 Email
- [ ] Serotonin Persistent TCP
- [x] SNMP
- [ ] SQL Data Source
- [ ] Tango
- [x] Virtual Data Source
- [ ] VMStat Data Source

![DataSourceVueMap](https://user-images.githubusercontent.com/22638815/130083115-226dc033-72e4-41e8-b345-6595b620bc60.png)

## Main View with DataSource table:
![overview](https://user-images.githubusercontent.com/22638815/130085065-26cf08cc-e18c-4197-8545-bd841d874a66.png)
It is sortable so it is easy to find a specific DataSource. On the top right corner there is a "Add" button to create a new Data source.

### Data Source creation:
When that button is clicked the Dialog is showing up. This is dynamic component that depending on the selected Data Source type from the select-box in the up-right corner of that dialog change the configuration. This example present the Virtual Data Source settings:
![ds_creation](https://user-images.githubusercontent.com/22638815/130085300-2f5c6169-fb2d-42fe-8c60-508a4a8b7eee.png)

### Data Source edit
Next screen show us the Edit Data Source panel from SNMP Data Source. It base on the same "config.vue" template but it has different behaviour and labels. Adding a new type of Data Source is quite easy becouse it require only adding a new module inside vue components and import it in a specific location.
![ds_edit](https://user-images.githubusercontent.com/22638815/130085648-553bb33d-4403-4947-81af-e5eaee5eca3a.png)

### Data Point creation
Each data source after creation contains no data. So there is another pop-up that is responsible for creating a Data Point. On that example is presented the Virtual Data Point with Numeric value type that has opened Change Type select box. You can see that there is a validation on Data Point Name field marked. Until it is empty user will not be able to save that Data Point
![dp_creation](https://user-images.githubusercontent.com/22638815/130085991-8f854bbb-d82d-4743-8fe1-1949165b05c7.png)

### Data Point edition
This picture presents the Data Point Creation dialog much better. But this time this dialog is responisble for editing component data. It has plenty of combinations inside but that is only a brief summary how it looks like now.
![dp_edit](https://user-images.githubusercontent.com/22638815/130086400-f3963c2d-b2cb-411c-8fa7-4fe4901bd6be.png)
