### ISSUE TITLE
Expansion of support for the DNP3 protocol

### ISSUE THREAD

**Issue by Limraj** [SCADA-LTS/Scada-LTS#2547]
- [ ] https://github.com/SCADA-LTS/Scada-LTS/issues/2542
- [ ] https://github.com/SCADA-LTS/Scada-LTS/issues/464
- [ ] https://github.com/SCADA-LTS/Scada-LTS/issues/2098
